file-picker-title-open-file = Buka satu berkas
file-picker-title-open-directory = Buka Folder
file-picker-filter-supported = Berkas Yang Didukung
file-picker-filter-swf = SWF (*.swf)
file-picker-filter-spl = FutureSplash Animator (*.spl)
file-picker-filter-ruf = Bundle Ruffle (*.ruf)
file-picker-filter-all = Semua Berkas
file-picker-select-root-movie-title = Pilih Movie Utama
file-picker-select-root-movie-message = Silakan pilih movie utama pada direktori yang dibuka.
file-picker-select-root-movie-select = Pilih
