[package]
name = "ruffle_soak"
edition.workspace = true
version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
ruffle_core = { path = "../../core", features = ["default_font", "audio", "mp3"] }
ruffle_render = { path = "../../render" }
ruffle_render_wgpu = { path = "../../render/wgpu" }
anyhow = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
